/* 138A-12 — Límites del contrato de cielo (skydome procedural). Constantes
 * puras separadas de sky-options.ts para mantener el módulo principal bajo
 * el umbral de meta (<300 líneas efectivas). */

/** Rangos del contrato de cielo: mínimo/máximo por campo numérico. */
export const SKY_LIMITS = {
  minMode: 0,
  maxMode: 2,
  minHighStart: -0.2,
  maxHighStart: 0.8,
  minBandTop: 0.05,
  maxBandTop: 1,
  minBandLow: -0.8,
  maxBandLow: 0.2,
  minCoverage: 0,
  maxCoverage: 1,
  minScale: 0.5,
  maxScale: 9,
  minSquash: 0.5,
  maxSquash: 3.5,
  minPuff: 0,
  maxPuff: 1,
  minEdge: 0.004,
  maxEdge: 0.3,
  minWarp: 0,
  maxWarp: 1.2,
  minOctaves: 2,
  maxOctaves: 8,
  minBands: 2,
  maxBands: 14,
  minPosterize: 0,
  maxPosterize: 1,
  minShadowStr: 0,
  maxShadowStr: 2,
  minStepScale: 0.05,
  maxStepScale: 0.9,
  minSilver: 0,
  maxSilver: 1.5,
  minL2Coverage: 0,
  maxL2Coverage: 1,
  minL2Scale: 0.4,
  maxL2Scale: 3,
  minL2Opacity: 0,
  maxL2Opacity: 1,
  minHaze: 0,
  maxHaze: 1,
  minSunEl: -12,
  maxSunEl: 90,
  minSunAz: 0,
  maxSunAz: 360,
  minSunInfluence: 0,
  maxSunInfluence: 1.5,
  minSunSize: 0.3,
  maxSunSize: 8,
  minSunGlow: 0,
  maxSunGlow: 1,
  minDrift: 0,
  maxDrift: 0.12,
  minEvolve: 0,
  maxEvolve: 2,
  minSeed: 0,
  maxSeed: 500,
} as const;
